
const productReducerConstant ={
    PRODUCT_LIST_REQUEST:'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS:'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_ERROR:'PRODUCT_LIST_ERROR',
    PRODUCT_FETCH_REQUEST:'PRODUCT_FETCH_REQUEST',
    PRODUCT_FETCH_SUCCESS:'PRODUCT_FETCH_SUCCESS',
    PRODUCT_FETCH_ERROR:'PRODUCT_FETCH_ERROR',
    

} 

export default productReducerConstant;